#Criando um serviceAccount
apiVersion: v1
kind: ServiceAccount
metadata:
  name: server

---
#Criando uma Role
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: server-reader
rules:
  - apiGroups: [""] # "" indicates the core API group
    resources: ["pods"]
    verbs: ["get", "watch", "list"]
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "watch", "list"]

---
# Atribuildo uma Rule para um serviceAccount
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: server-rule-bind
subjects:
  - kind: ServiceAccount
    name: server
    namespace: dev
roleRef:
  kind: Role
  name: server-reader
  apiGroup: rbac.authorization.k8s.io
