apiVersion: v1
kind: Service
metadata:
  name: mysql-h # nome do serviço tem que ser igual ao nome dado ao serviceName no StatefulSet
spec:
  selector:
    app: mysql
  ports:
    - port: 3306
  clusterIP: None
