apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  serviceName: mysql-h # é obrigatório por conta do headless service
  replicas: 2
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: myapp
          image: mysql
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: root

          volumeMounts:
            - mountPath: "/var/lib/mysql"
              name: mysql-volume

  volumeClaimTemplates:
    - metadata:
        name: mysql-volume
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi
# metadata:
#   name: mystatefulset
# spec:
#   selector:
#     matchLabels:
#       app: myapp
#   serviceName: <ServiceName>
#   replicas: 2
#   template:
#     metadata:
#       labels:
#         app: myapp
#     spec:
#       containers:
#       - name: myapp
#         image: k8s.gcr.io/nginx-slim:0.8
#         ports:
#         - containerPort: 80
#           name: web
#         volumeMounts:
#         - name: www
#           mountPath: /usr/share/nginx/html
#   volumeClaimTemplates:
#   - metadata:
#       name: www
#     spec:
#       accessModes: [ "ReadWriteOnce" ]
#       resources:
#         requests:
#           storage: 1Gi
